version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8082}:${INTERNAL_PORT:-80}"
    restart: unless-stopped
    env_file:
      - .env
