// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tquredrvexziwipkonhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxdXJlZHJ2ZXh6aXdpcGtvbmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4Njc3ODgsImV4cCI6MjA0OTQ0Mzc4OH0.fuqUW18HqLOSKdiEHBIQYd-AkSwsTqLoLvnI794341E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);